package jiconfont.icons;

import jiconfont.IconCode;
import jiconfont.IconFont;

import java.io.InputStream;

/**
 * Copyright (c) 2016 jIconFont <BR>
 * <BR>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:<BR>
 * <BR>
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.<BR>
 * <BR>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
public enum Elusive implements IconCode {

    ADDRESS_BOOK('\uE729'),
    ADDRESS_BOOK_ALT('\uE728'),
    ADJUST('\uE727'),
    ADJUST_ALT('\uE726'),
    ADULT('\uE725'),
    ALIGN_CENTER('\uE724'),
    ALIGN_JUSTIFY('\uE723'),
    ALIGN_LEFT('\uE722'),
    ALIGN_RIGHT('\uE721'),
    ARROW_DOWN('\uE720'),
    ARROW_LEFT('\uE71F'),
    ARROW_RIGHT('\uE71E'),
    ARROW_UP('\uE71D'),
    ASL('\uE71C'),
    ASTERISK('\uE72A'),
    BACKWARD('\uE71B'),
    BAN_CIRCLE('\uE71A'),
    BARCODE('\uE719'),
    BEHANCE('\uE718'),
    BELL('\uE717'),
    BLIND('\uE716'),
    BLOGGER('\uE715'),
    BOLD('\uE714'),
    BOOK('\uE713'),
    BOOKMARK('\uE712'),
    BOOKMARK_EMPTY('\uE711'),
    BRAILLE('\uE710'),
    BRIEFCASE('\uE70F'),
    BROOM('\uE70E'),
    BRUSH('\uE70D'),
    BULB('\uE70C'),
    BULLHORN('\uE70B'),
    CALENDAR('\uE70A'),
    CALENDAR_SIGN('\uE709'),
    CAMERA('\uE708'),
    CAR('\uE707'),
    CARET_DOWN('\uE706'),
    CARET_LEFT('\uE705'),
    CARET_RIGHT('\uE704'),
    CARET_UP('\uE703'),
    CC('\uE702'),
    CERTIFICATE('\uE701'),
    CHECK('\uE700'),
    CHECK_EMPTY('\uE6FF'),
    CHEVRON_DOWN('\uE6FE'),
    CHEVRON_LEFT('\uE6FD'),
    CHEVRON_RIGHT('\uE6FC'),
    CHEVRON_UP('\uE6FB'),
    CHILD('\uE6FA'),
    CIRCLE_ARROW_DOWN('\uE6F9'),
    CIRCLE_ARROW_LEFT('\uE6F8'),
    CIRCLE_ARROW_RIGHT('\uE6F7'),
    CIRCLE_ARROW_UP('\uE6F6'),
    CLOUD('\uE6F5'),
    CLOUD_ALT('\uE6F4'),
    COG('\uE6F3'),
    COGS('\uE6F1'),
    COG_ALT('\uE6F2'),
    COMMENT('\uE6F0'),
    COMMENT_ALT('\uE6EF'),
    COMPASS('\uE6EE'),
    COMPASS_ALT('\uE6ED'),
    CREDIT_CARD('\uE6EC'),
    CSS('\uE6EB'),
    DASHBOARD('\uE6EA'),
    DELICIOUS('\uE6E9'),
    DEVIANTART('\uE6E8'),
    DIGG('\uE6E7'),
    DOWNLOAD('\uE6E6'),
    DOWNLOAD_ALT('\uE6E5'),
    DRIBBBLE('\uE6E4'),
    EARPHONE('\uE66E'),
    EDIT('\uE6E3'),
    EJECT('\uE6E2'),
    ENVELOPE('\uE6E1'),
    ENVELOPE_ALT('\uE6E0'),
    ERROR('\uE6DF'),
    ERROR_ALT('\uE6DE'),
    EUR('\uE6DD'),
    EXCLAMATION_SIGN('\uE6DC'),
    EYE_CLOSE('\uE6DB'),
    EYE_OPEN('\uE6DA'),
    FACEBOOK('\uE6D9'),
    FACETIME_VIDEO('\uE6D8'),
    FAST_BACKWARD('\uE6D7'),
    FAST_FORWARD('\uE6D6'),
    FEMALE('\uE6D5'),
    FILE('\uE6D4'),
    FILE_ALT('\uE6D3'),
    FILE_EDIT('\uE6D2'),
    FILE_EDIT_ALT('\uE6D1'),
    FILE_NEW('\uE6D0'),
    FILE_NEW_ALT('\uE6CF'),
    FILM('\uE6CE'),
    FILTER('\uE6CD'),
    FIRE('\uE6CC'),
    FLAG('\uE6CB'),
    FLAG_ALT('\uE6CA'),
    FLICKR('\uE6C9'),
    FOLDER('\uE6C8'),
    FOLDER_CLOSE('\uE6C7'),
    FOLDER_OPEN('\uE6C6'),
    FOLDER_SIGN('\uE6C5'),
    FONT('\uE6C4'),
    FONTSIZE('\uE6C3'),
    FORK('\uE6C2'),
    FORWARD('\uE6C1'),
    FORWARD_ALT('\uE6C0'),
    FOURSQUARE('\uE6BF'),
    FRIENDFEED('\uE6BE'),
    FRIENDFEED_RECT('\uE6BD'),
    FULLSCREEN('\uE6BC'),
    GBP('\uE6BB'),
    GIFT('\uE6BA'),
    GITHUB('\uE6B9'),
    GITHUB_TEXT('\uE6B8'),
    GLASS('\uE6B7'),
    GLASSES('\uE6B6'),
    GLOBE('\uE6B5'),
    GLOBE_ALT('\uE6B4'),
    GOOGLEPLUS('\uE6B3'),
    GRAPH('\uE6B2'),
    GRAPH_ALT('\uE6B1'),
    GROUP('\uE6B0'),
    GROUP_ALT('\uE6AF'),
    GUIDEDOG('\uE6AE'),
    HAND_DOWN('\uE6AD'),
    HAND_LEFT('\uE6AC'),
    HAND_RIGHT('\uE6AB'),
    HAND_UP('\uE6AA'),
    HDD('\uE6A9'),
    HEADPHONES('\uE6A8'),
    HEARING_IMPAIRED('\uE6A7'),
    HEART('\uE6A6'),
    HEART_ALT('\uE6A5'),
    HEART_EMPTY('\uE6A4'),
    HOME('\uE6A3'),
    HOME_ALT('\uE6A2'),
    HOURGLASS('\uE6A1'),
    IDEA('\uE6A0'),
    IDEA_ALT('\uE69F'),
    INBOX('\uE69E'),
    INBOX_ALT('\uE69D'),
    INBOX_BOX('\uE69C'),
    INDENT_LEFT('\uE69B'),
    INDENT_RIGHT('\uE69A'),
    INFO_SIGN('\uE699'),
    INSTAGRAM('\uE698'),
    IPHONE_HOME('\uE697'),
    ITALIC('\uE696'),
    KEY('\uE695'),
    LAPTOP('\uE694'),
    LAPTOP_ALT('\uE693'),
    LASTFM('\uE692'),
    LEAF('\uE691'),
    LINES('\uE690'),
    LINK('\uE68F'),
    LINKEDIN('\uE68E'),
    LIST('\uE68D'),
    LIST_ALT('\uE68C'),
    LIVEJOURNAL('\uE68B'),
    LOCK('\uE68A'),
    LOCK_ALT('\uE689'),
    MAGIC('\uE688'),
    MAGNET('\uE687'),
    MALE('\uE686'),
    MAP_MARKER('\uE685'),
    MAP_MARKER_ALT('\uE684'),
    MIC('\uE683'),
    MIC_ALT('\uE682'),
    MINUS('\uE681'),
    MINUS_SIGN('\uE680'),
    MOVE('\uE67F'),
    MUSIC('\uE67E'),
    MYSPACE('\uE67D'),
    NETWORK('\uE67C'),
    OFF('\uE67B'),
    OK('\uE67A'),
    OK_CIRCLE('\uE679'),
    OK_SIGN('\uE678'),
    OPENSOURCE('\uE677'),
    PAPERCLIP('\uE676'),
    PAPERCLIP_ALT('\uE675'),
    PAPER_CLIP('\uE676'),
    PAPER_CLIP_ALT('\uE675'),
    PATH('\uE674'),
    PAUSE('\uE673'),
    PAUSE_ALT('\uE672'),
    PENCIL('\uE671'),
    PENCIL_ALT('\uE670'),
    PERSON('\uE66F'),
    PHONE('\uE66E'),
    PHONE_ALT('\uE66D'),
    PHOTO('\uE66C'),
    PHOTO_ALT('\uE66B'),
    PICASA('\uE66A'),
    PICTURE('\uE669'),
    PINTEREST('\uE668'),
    PLANE('\uE667'),
    PLAY('\uE666'),
    PLAY_ALT('\uE665'),
    PLAY_CIRCLE('\uE664'),
    PLUS('\uE663'),
    PLUS_SIGN('\uE662'),
    PODCAST('\uE661'),
    PRINT('\uE660'),
    PUZZLE('\uE65F'),
    QRCODE('\uE65E'),
    QUESTION('\uE65D'),
    QUESTION_SIGN('\uE65C'),
    QUOTES('\uE65B'),
    QUOTES_ALT('\uE65A'),
    RANDOM('\uE659'),
    RECORD('\uE658'),
    REDDIT('\uE657'),
    REFRESH('\uE656'),
    REMOVE('\uE655'),
    REMOVE_CIRCLE('\uE654'),
    REMOVE_SIGN('\uE653'),
    REPEAT('\uE652'),
    REPEAT_ALT('\uE651'),
    RESIZE_FULL('\uE650'),
    RESIZE_HORIZONTAL('\uE64F'),
    RESIZE_SMALL('\uE64E'),
    RESIZE_VERTICAL('\uE64D'),
    RETURN_KEY('\uE64C'),
    RETWEET('\uE64B'),
    REVERSE_ALT('\uE64A'),
    ROAD('\uE649'),
    RSS('\uE648'),
    SCISSORS('\uE647'),
    SCREEN('\uE646'),
    SCREENSHOT('\uE644'),
    SCREEN_ALT('\uE645'),
    SEARCH('\uE643'),
    SEARCH_ALT('\uE642'),
    SHARE('\uE641'),
    SHARE_ALT('\uE640'),
    SHOPPING_CART('\uE63F'),
    SHOPPING_CART_SIGN('\uE63E'),
    SIGNAL('\uE63D'),
    SKYPE('\uE63C'),
    SLIDESHARE('\uE63B'),
    SMILEY('\uE63A'),
    SMILEY_ALT('\uE639'),
    SOUNDCLOUD('\uE638'),
    SPEAKER('\uE637'),
    SPOTIFY('\uE636'),
    STACKOVERFLOW('\uE635'),
    STAR('\uE634'),
    STAR_ALT('\uE633'),
    STAR_EMPTY('\uE632'),
    STEP_BACKWARD('\uE631'),
    STEP_FORWARD('\uE630'),
    STOP('\uE62F'),
    STOP_ALT('\uE62E'),
    STUMBLEUPON('\uE62D'),
    TAG('\uE62C'),
    TAGS('\uE62B'),
    TASKS('\uE62A'),
    TEXT_HEIGHT('\uE629'),
    TEXT_WIDTH('\uE628'),
    TH('\uE627'),
    THUMBS_DOWN('\uE624'),
    THUMBS_UP('\uE623'),
    TH_LARGE('\uE626'),
    TH_LIST('\uE625'),
    TIME('\uE622'),
    TIME_ALT('\uE621'),
    TINT('\uE620'),
    TORSO('\uE61F'),
    TRASH('\uE61E'),
    TRASH_ALT('\uE61D'),
    TUMBLR('\uE61C'),
    TWITTER('\uE61B'),
    UNCHECKED('\uE6FF'),
    UNIVERSAL_ACCESS('\uE61A'),
    UNLOCK('\uE619'),
    UNLOCK_ALT('\uE618'),
    UPLOAD('\uE617'),
    USD('\uE616'),
    USER('\uE615'),
    VIADEO('\uE614'),
    VIDEO('\uE613'),
    VIDEO_ALT('\uE612'),
    VIDEO_CHAT('\uE611'),
    VIEW_MODE('\uE610'),
    VIMEO('\uE60F'),
    VKONTAKTE('\uE60E'),
    VOLUME_DOWN('\uE60D'),
    VOLUME_OFF('\uE60C'),
    VOLUME_UP('\uE60B'),
    W3C('\uE60A'),
    WARNING_SIGN('\uE609'),
    WEBSITE('\uE608'),
    WEBSITE_ALT('\uE607'),
    WHEELCHAIR('\uE606'),
    WORDPRESS('\uE605'),
    WRENCH('\uE604'),
    WRENCH_ALT('\uE603'),
    YOUTUBE('\uE602'),
    ZOOM_IN('\uE601'),
    ZOOM_OUT('\uE600');

    private final char character;

    Elusive(char character) {
        this.character = character;
    }

    @Override
    public char getUnicode() {
        return character;
    }

    @Override
    public String getFontFamily() {
        return "Elusive-Icons";
    }

    public static IconFont getIconFont() {
        return new IconFont() {
            @Override
            public String getFontFamily() {
                return "Elusive-Icons";
            }

            @Override
            public InputStream getFontInputStream() {
                return Elusive.class.getResourceAsStream("/fonts/Elusive-Icons.ttf");
            }
        };
    }

}
